// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVqR1Q-nCcZazjEj55Ke7ycIxzAE13Mjk',
    appId: '1:653337980553:android:bd9e37d76e6613e1e46058',
    messagingSenderId: '653337980553',
    projectId: 'al-ghazawi',
    databaseURL: 'https://al-ghazawi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'al-ghazawi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGrZ3NGg8iKGkAZTGPaKoCvKskyMYhgdI',
    appId: '1:653337980553:ios:dabc5300a86ab0b3e46058',
    messagingSenderId: '653337980553',
    projectId: 'al-ghazawi',
    databaseURL: 'https://al-ghazawi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'al-ghazawi.firebasestorage.app',
    iosBundleId: 'com.alqhazawi.app.alqhazawi',
  );

}